### ISSUE TITLE
Typo in bom.csv

### ISSUE THREAD

**Issue by Arunas-g** [JanM321/esphome-lg-controller#17]
In the file hardware-tiny/production/bom.csv there is a typo in the line "C2", column "LCSC Part #". I believe that the order number is not correct (duplicated with the line "C5")

**Comment by JanM321** [comment]
CC @florianbrede-ayet

**Comment by florianbrede-ayet** [comment]
@Arunas-g, thanks for pointing it out.
I made a mistake during LCSC assignment and fixed the BOM with the correct capacitor.
Luckily, my boards still turned out fine, because C2 is just controlling the rise-time of the step-down converter.

I still changed the part since the datasheet recommends 3.3nF.

**Comment by JanM321** [comment]
That was fast. Closing this issue.
