### ISSUE TITLE
Would this work with a LG WH27S?

### ISSUE THREAD

**Issue by PvdGulik** [JanM321/esphome-lg-controller#54]
Hello, verry intresting project. I have a WH27S waterpumpboiler, which has a CN_REMO connector.
Do you think this project would work?

Thanks!

![image](https://github.com/JanM321/esphome-lg-controller/assets/9421474/693bf84e-2fd0-47b2-ace5-c31d8a44d584)

**Comment by JanM321** [comment]
The hardware side is probably similar, but I expect the protocol to be different.

This looks relevant: https://github.com/cribskip/esp8266_lgawhp ?

**Comment by PvdGulik** [comment]
I do have a HM093MR.U44. This works perfectly with https://github.com/paqpaqpaq/ThermaV_overshoot_logic or with the above one.
But now I 'm  looking for a LG WH27S.F5 which does not have a modbus connection, as the above one needs.
That's why a found yours. Could I try to use the CN_REMO connection without breaking my WaterPumpboiler?

Thanks!

**Comment by JanM321** [comment]
> Could I try to use the CN_REMO connection without breaking my WaterPumpboiler?

I can't tell you this because I know nothing about this kind of device. Do you know if LG has official CN-REMO controllers for it? There's not a lot of information available.

If it's a 12V connection similar to the one for AC units it __probably__ won't break it, but I would be surprised if it uses the same protocol as the one implemented here. LG also used different protocols for AC units and ventilation products for example (see issue #33).

**Comment by JanM321** [comment]
Closing because out of scope for this project if it uses a different protocol.
